#!/bin/bash
# Test URL patterns for all subjects across all grades

echo "========================================="
echo "Testing NCERT URL Patterns - All Subjects"
echo "========================================="
echo ""

echo "GRADE 10:"
echo "---------"
curl -s -I "https://ncert.nic.in/textbook/pdf/jemh101.pdf" 2>/dev/null | grep -q "200 OK" && echo "✅ Mathematics (jemh1)" || echo "❌ Mathematics"
curl -s -I "https://ncert.nic.in/textbook/pdf/jesc101.pdf" 2>/dev/null | grep -q "200 OK" && echo "✅ Science (jesc1)" || echo "❌ Science"
curl -s -I "https://ncert.nic.in/textbook/pdf/jess101.pdf" 2>/dev/null | grep -q "200 OK" && echo "✅ Social Science (jess1)" || echo "❌ Social Science"
curl -s -I "https://ncert.nic.in/textbook/pdf/jehs101.pdf" 2>/dev/null | grep -q "200 OK" && echo "✅ History (jehs1)" || echo "❌ History"
curl -s -I "https://ncert.nic.in/textbook/pdf/jegy101.pdf" 2>/dev/null | grep -q "200 OK" && echo "✅ Geography (jegy1)" || echo "❌ Geography"
curl -s -I "https://ncert.nic.in/textbook/pdf/jeps101.pdf" 2>/dev/null | grep -q "200 OK" && echo "✅ Political Science (jeps1)" || echo "❌ Political Science"
curl -s -I "https://ncert.nic.in/textbook/pdf/jeec101.pdf" 2>/dev/null | grep -q "200 OK" && echo "✅ Economics (jeec1)" || echo "❌ Economics"
curl -s -I "https://ncert.nic.in/textbook/pdf/jeel101.pdf" 2>/dev/null | grep -q "200 OK" && echo "✅ English First Flight (jeel1)" || echo "❌ English First Flight"
curl -s -I "https://ncert.nic.in/textbook/pdf/jeep101.pdf" 2>/dev/null | grep -q "200 OK" && echo "✅ English Footprints (jeep1)" || echo "❌ English Footprints"
curl -s -I "https://ncert.nic.in/textbook/pdf/jhkt101.pdf" 2>/dev/null | grep -q "200 OK" && echo "✅ Hindi Kshitij (jhkt1)" || echo "❌ Hindi Kshitij"
curl -s -I "https://ncert.nic.in/textbook/pdf/jhsp101.pdf" 2>/dev/null | grep -q "200 OK" && echo "✅ Hindi Sparsh (jhsp1)" || echo "❌ Hindi Sparsh"
curl -s -I "https://ncert.nic.in/textbook/pdf/jhsn101.pdf" 2>/dev/null | grep -q "200 OK" && echo "✅ Hindi Sanchayan (jhsn1)" || echo "❌ Hindi Sanchayan"
echo ""

echo "GRADE 9:"
echo "--------"
curl -s -I "https://ncert.nic.in/textbook/pdf/iemh101.pdf" 2>/dev/null | grep -q "200 OK" && echo "✅ Mathematics (iemh1)" || echo "❌ Mathematics"
curl -s -I "https://ncert.nic.in/textbook/pdf/iesc101.pdf" 2>/dev/null | grep -q "200 OK" && echo "✅ Science (iesc1)" || echo "❌ Science"
curl -s -I "https://ncert.nic.in/textbook/pdf/iess101.pdf" 2>/dev/null | grep -q "200 OK" && echo "✅ Social Science (iess1)" || echo "❌ Social Science"
curl -s -I "https://ncert.nic.in/textbook/pdf/iehs101.pdf" 2>/dev/null | grep -q "200 OK" && echo "✅ History (iehs1)" || echo "❌ History"
curl -s -I "https://ncert.nic.in/textbook/pdf/iegy101.pdf" 2>/dev/null | grep -q "200 OK" && echo "✅ Geography (iegy1)" || echo "❌ Geography"
curl -s -I "https://ncert.nic.in/textbook/pdf/ieps101.pdf" 2>/dev/null | grep -q "200 OK" && echo "✅ Political Science (ieps1)" || echo "❌ Political Science"
curl -s -I "https://ncert.nic.in/textbook/pdf/ieec101.pdf" 2>/dev/null | grep -q "200 OK" && echo "✅ Economics (ieec1)" || echo "❌ Economics"
curl -s -I "https://ncert.nic.in/textbook/pdf/ieel101.pdf" 2>/dev/null | grep -q "200 OK" && echo "✅ English Beehive (ieel1)" || echo "❌ English Beehive"
curl -s -I "https://ncert.nic.in/textbook/pdf/ieep101.pdf" 2>/dev/null | grep -q "200 OK" && echo "✅ English Moments (ieep1)" || echo "❌ English Moments"
curl -s -I "https://ncert.nic.in/textbook/pdf/ihkt101.pdf" 2>/dev/null | grep -q "200 OK" && echo "✅ Hindi Kshitij (ihkt1)" || echo "❌ Hindi Kshitij"
curl -s -I "https://ncert.nic.in/textbook/pdf/ihsp101.pdf" 2>/dev/null | grep -q "200 OK" && echo "✅ Hindi Sparsh (ihsp1)" || echo "❌ Hindi Sparsh"
echo ""

echo "GRADE 8:"
echo "--------"
curl -s -I "https://ncert.nic.in/textbook/pdf/hemh101.pdf" 2>/dev/null | grep -q "200 OK" && echo "✅ Mathematics (hemh1)" || echo "❌ Mathematics"
curl -s -I "https://ncert.nic.in/textbook/pdf/hesc101.pdf" 2>/dev/null | grep -q "200 OK" && echo "✅ Science (hesc1)" || echo "❌ Science"
curl -s -I "https://ncert.nic.in/textbook/pdf/hess101.pdf" 2>/dev/null | grep -q "200 OK" && echo "✅ Social Science (hess1)" || echo "❌ Social Science"
curl -s -I "https://ncert.nic.in/textbook/pdf/heel101.pdf" 2>/dev/null | grep -q "200 OK" && echo "✅ English Honeydew (heel1)" || echo "❌ English Honeydew"
curl -s -I "https://ncert.nic.in/textbook/pdf/heep101.pdf" 2>/dev/null | grep -q "200 OK" && echo "✅ English It So Happened (heep1)" || echo "❌ English It So Happened"
curl -s -I "https://ncert.nic.in/textbook/pdf/hhvs101.pdf" 2>/dev/null | grep -q "200 OK" && echo "✅ Hindi Vasant (hhvs1)" || echo "❌ Hindi Vasant"
echo ""
